version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
      
  users-service:
    build: ./services/users-service
    restart: always
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PORT: 5000
      NOTIFICATIONS_URL: http://notifications-service:6000/api/notifications
      RABBITMQ_URL: amqp://rabbitmq
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/users-service:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run dev"
    
  api-gateway:
    build: ./services/gateway-service 
    restart: always
    environment:
      PORT: 8000
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - users-service
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  notifications-service:
    build: ./services/notifications-service
    restart: always
    environment:
      PORT: 6000
      RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "6000:6000"
    depends_on:
      - rabbitmq

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: